# Generated by Django 5.2.8 on 2026-09-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='closing_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='institution',
            name='is_currently_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='opening_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='working_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
