# Generated by Django 5.2.8 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_institution_closing_hours_institution_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, upload_to='institution_logos/'),
        ),
    ]
