# Generated by Django 5.2.8 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_citizenprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures/'),
        ),
    ]
