# Generated by Django 5.2.8 on 2026-09-13 22:09

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_alter_institution_logo'),
        ('tickets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='queue_date',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('service', 'queue_date', 'number'), name='unique_daily_service_ticket_number'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['waiting', 'called'])), fields=('user',), name='one_active_ticket_per_user'),
        ),
    ]
